# Generated by Django 4.1.7 on 2023-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(default=0, verbose_name='driver id')),
                ('status', models.CharField(max_length=100, verbose_name='status of entry')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('total', models.DurationField()),
                ('break_in', models.IntegerField(blank=True, null=True, verbose_name='break_in')),
                ('drive', models.IntegerField(blank=True, null=True, verbose_name='drive')),
                ('shift', models.IntegerField(blank=True, null=True, verbose_name='shift')),
                ('cycle', models.IntegerField(blank=True, null=True, verbose_name='cycle')),
                ('last_day_off_duty', models.CharField(blank=True, max_length=100, null=True, verbose_name='last day off duty')),
                ('last_day_sleeper', models.CharField(blank=True, max_length=100, null=True, verbose_name='last day sleeper')),
                ('last_day_drive', models.CharField(blank=True, max_length=100, null=True, verbose_name='last day drive')),
                ('last_day_on_duty', models.CharField(max_length=100, verbose_name='last day on duty')),
                ('fresh', models.BooleanField(default=False, verbose_name='fresh')),
            ],
        ),
    ]
